// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzoW4wosoYDct5g3da0mfdPS9gQnP4I7k',
    appId: '1:189309535442:web:2897f4b2d252e2d825990b',
    messagingSenderId: '189309535442',
    projectId: 'oasis-app-delivery',
    authDomain: 'oasis-app-delivery.firebaseapp.com',
    databaseURL: 'https://oasis-app-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'oasis-app-delivery.appspot.com',
    measurementId: 'G-SZL6KBFCZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmZLa_noY1m3IC2m7IZnarzaKVBLV-jo',
    appId: '1:189309535442:android:f398ca2956b23b2d25990b',
    messagingSenderId: '189309535442',
    projectId: 'oasis-app-delivery',
    databaseURL: 'https://oasis-app-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'oasis-app-delivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEsUxhxm5gCltml-JSNPE6wQp4pA_FC8s',
    appId: '1:189309535442:ios:6ee560394e6b072125990b',
    messagingSenderId: '189309535442',
    projectId: 'oasis-app-delivery',
    databaseURL: 'https://oasis-app-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'oasis-app-delivery.appspot.com',
    androidClientId: '189309535442-sv5tgr59fe3q6b2u4ml0d8go87vpl2bk.apps.googleusercontent.com',
    iosClientId: '189309535442-6kmp1o3o04j46ja6q3hj23q665418qdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.trillestAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEsUxhxm5gCltml-JSNPE6wQp4pA_FC8s',
    appId: '1:189309535442:ios:6ee560394e6b072125990b',
    messagingSenderId: '189309535442',
    projectId: 'oasis-app-delivery',
    databaseURL: 'https://oasis-app-delivery-default-rtdb.firebaseio.com',
    storageBucket: 'oasis-app-delivery.appspot.com',
    androidClientId: '189309535442-sv5tgr59fe3q6b2u4ml0d8go87vpl2bk.apps.googleusercontent.com',
    iosClientId: '189309535442-6kmp1o3o04j46ja6q3hj23q665418qdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.trillestAdmin',
  );
}
